#############################################################################
# Makefile for building: RainbowTable
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  RainbowTable.pro
# Template: app
# Command: /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/bin/qmake -o Makefile RainbowTable.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/macx-clang
QMAKE         = /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RainbowTable1.0.0
DISTDIR = /Users/leopoldmols/Documents/QTCreator/ESI/2eme/SECL/RainbowTable/temp/rainbowTable/.tmp/RainbowTable1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS)    
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sha256-main.cpp \
		sha256.cpp \
		tableGeneration.cpp \
		uncypher.cpp 
OBJECTS       = sha256-main.o \
		sha256.o \
		tableGeneration.o \
		uncypher.o
DIST          = /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/qdevice.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/device_config.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/unix.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/mac.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/macx.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/clang.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/qconfig.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/default_post.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/mac.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/yacc.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/lex.prf \
		RainbowTable.pro passwd-utils.hpp \
		random.hpp \
		sha256.h \
		tableGeneration.h \
		uncypher.h sha256-main.cpp \
		sha256.cpp \
		tableGeneration.cpp \
		uncypher.cpp
QMAKE_TARGET  = RainbowTable
DESTDIR       = 
TARGET        = RainbowTable

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/leopoldmols/Documents/QTCreator/ESI/2eme/SECL/RainbowTable/temp/rainbowTable/RainbowTable.pro


include /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

RainbowTable:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RainbowTable.pro /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/qdevice.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/device_config.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/unix.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/mac.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/macx.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/clang.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/qconfig.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/default_post.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/mac.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/yacc.prf \
		/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/lex.prf \
		RainbowTable.pro
	$(QMAKE) -o Makefile RainbowTable.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/qdevice.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/device_config.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/unix.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/mac.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/macx.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/sanitize.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/clang.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/qconfig.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qt_config.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/toolchain.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/default_pre.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/default_post.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qml_debug.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/mac.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/warn_on.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/file_copies.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/exceptions.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/yacc.prf:
/Users/leopoldmols/Documents/QTCreator/5.12.8/clang_64/mkspecs/features/lex.prf:
RainbowTable.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile RainbowTable.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile RainbowTable

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

sha256-main.o: sha256-main.cpp sha256.h \
		tableGeneration.h \
		uncypher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha256-main.o sha256-main.cpp

sha256.o: sha256.cpp sha256.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha256.o sha256.cpp

tableGeneration.o: tableGeneration.cpp passwd-utils.hpp \
		random.hpp \
		sha256.h \
		tableGeneration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableGeneration.o tableGeneration.cpp

uncypher.o: uncypher.cpp uncypher.h \
		sha256.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uncypher.o uncypher.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/RainbowTable/bin || mkdir -p $(INSTALL_ROOT)/opt/RainbowTable/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/RainbowTable/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/RainbowTable/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/RainbowTable/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

